### ISSUE TITLE
Still getting warning about Object.observe

### ISSUE THREAD

**Issue by ffxsam** [JackAdams/constellation-session#2]
> 'Object.observe' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/6147094632988672 for more details.

I seem to remember this being fixed, but I don't see any issues or PRs about it. I'm still seeing this warning.

**Comment by JackAdams** [comment]
Yes, likewise.  I could swear this was fixed in a PR just a few weeks ago.

**Comment by JackAdams** [comment]
Ahh... that was in `constellation:subscriptions`.  I forgot that `Object.observe` was in this package as well.  Feel free to create a PR that removes it.  I'll accept it and publish the new version asap.

**Comment by ffxsam** [comment]
Done! https://github.com/JackAdams/constellation-session/pull/3
